name: Run test suite
on: push

jobs:
    run-tests:
        name: Run python unittest
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Testcontainers Cloud Client
              uses: atomicjar/testcontainers-cloud-setup-action@v1
              with: 
                token: ${{ secrets.TC_CLOUD_TOKEN }}
            
            - name: Testing
              run: python test.py
