name: Run test suite
on: push

jobs:
    run-tests:
        name: Run python unittest
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            
            - name: Testing
              run: python test.py
